"""metric snapshots

Revision ID: 3f97012ced38
Revises: ca8c13bf0ae9
Create Date: 2026-06-26 18:30:59.470857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '3f97012ced38'
down_revision: Union[str, None] = 'ca8c13bf0ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('social_media_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_account_id'), 'metric_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_captured_at'), 'metric_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_client_id'), 'metric_snapshots', ['client_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_metric'), 'metric_snapshots', ['metric'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_social_media_id'), 'metric_snapshots', ['social_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_social_media_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_metric'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_client_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_captured_at'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_account_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
