"""account plan_name

Revision ID: c426cc0ef8bd
Revises: b42e03470447
Create Date: 2026-06-26 15:20:52.167724
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c426cc0ef8bd'
down_revision: Union[str, None] = 'b42e03470447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accounts',
        sa.Column(
            'plan_name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='trial',  # backfills existing rows safely
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'plan_name')
    # ### end Alembic commands ###
