"""user 2fa fields

Revision ID: 905ea3a45f51
Revises: c426cc0ef8bd
Create Date: 2026-06-26 15:26:32.069004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '905ea3a45f51'
down_revision: Union[str, None] = 'c426cc0ef8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('recovery_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_codes')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
