/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/api/v1/auth/register": {
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/refresh": {
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/verify-email": {
    /** Verify Email */
    get: operations["verify_email_api_v1_auth_verify_email_get"];
  };
  "/api/v1/auth/forgot-password": {
    /** Forgot Password */
    post: operations["forgot_password_api_v1_auth_forgot_password_post"];
  };
  "/api/v1/auth/reset-password": {
    /** Reset Password */
    post: operations["reset_password_api_v1_auth_reset_password_post"];
  };
  "/api/v1/auth/change-password": {
    /** Change Password */
    post: operations["change_password_api_v1_auth_change_password_post"];
  };
  "/api/v1/account": {
    /** Get Account */
    get: operations["get_account_api_v1_account_get"];
    /** Update Account */
    put: operations["update_account_api_v1_account_put"];
  };
  "/api/v1/plans/{name}": {
    /** Get Plan */
    get: operations["get_plan_api_v1_plans__name__get"];
  };
  "/api/v1/leads": {
    /** List Leads */
    get: operations["list_leads_api_v1_leads_get"];
    /** Create Lead */
    post: operations["create_lead_api_v1_leads_post"];
  };
  "/api/v1/leads/search": {
    /** Search Leads */
    get: operations["search_leads_api_v1_leads_search_get"];
  };
  "/api/v1/leads/{lead_id}": {
    /** Get Lead */
    get: operations["get_lead_api_v1_leads__lead_id__get"];
    /** Update Lead */
    put: operations["update_lead_api_v1_leads__lead_id__put"];
    /** Delete Lead */
    delete: operations["delete_lead_api_v1_leads__lead_id__delete"];
  };
  "/api/v1/social": {
    /** List Tokens */
    get: operations["list_tokens_api_v1_social_get"];
    /** Save Token */
    post: operations["save_token_api_v1_social_post"];
  };
  "/api/v1/social/{platform}": {
    /** Get Token By Platform */
    get: operations["get_token_by_platform_api_v1_social__platform__get"];
  };
  "/api/v1/social/{token_id}": {
    /** Delete Token */
    delete: operations["delete_token_api_v1_social__token_id__delete"];
  };
  "/api/v1/ad-accounts": {
    /** List Ad Accounts */
    get: operations["list_ad_accounts_api_v1_ad_accounts_get"];
    /** Save Ad Account */
    post: operations["save_ad_account_api_v1_ad_accounts_post"];
  };
  "/api/v1/billing": {
    /** Get Billing */
    get: operations["get_billing_api_v1_billing_get"];
    /** Update Billing */
    put: operations["update_billing_api_v1_billing_put"];
  };
  "/api/v1/integrations/facebook/connect": {
    /** Facebook Connect */
    get: operations["facebook_connect_api_v1_integrations_facebook_connect_get"];
  };
  "/api/v1/integrations/facebook/callback": {
    /** Facebook Callback */
    get: operations["facebook_callback_api_v1_integrations_facebook_callback_get"];
  };
  "/api/v1/payments/create-subscription": {
    /** Create Subscription */
    post: operations["create_subscription_api_v1_payments_create_subscription_post"];
  };
  "/api/v1/payments/webhook": {
    /** Stripe Webhook */
    post: operations["stripe_webhook_api_v1_payments_webhook_post"];
  };
  "/api/v1/media/upload": {
    /** Upload Media */
    post: operations["upload_media_api_v1_media_upload_post"];
  };
  "/api/v1/scheduled-posts": {
    /** List Posts */
    get: operations["list_posts_api_v1_scheduled_posts_get"];
    /** Create Post */
    post: operations["create_post_api_v1_scheduled_posts_post"];
  };
  "/api/v1/scheduled-posts/{post_id}": {
    /** Get Post */
    get: operations["get_post_api_v1_scheduled_posts__post_id__get"];
    /** Cancel Post */
    delete: operations["cancel_post_api_v1_scheduled_posts__post_id__delete"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccountRead */
    AccountRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Account Name */
      account_name?: string | null;
      /** Account Type */
      account_type?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Users Limit */
      users_limit?: string | null;
      /** Logo */
      logo?: string | null;
      /** Trial Expiry */
      trial_expiry?: string | null;
      /** Is Account Paid */
      is_account_paid: boolean;
      /** On Hold */
      on_hold: boolean;
    };
    /** AccountUpdate */
    AccountUpdate: {
      /** Account Name */
      account_name?: string | null;
      /** Account Type */
      account_type?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Logo */
      logo?: string | null;
    };
    /** AdAccountCreate */
    AdAccountCreate: {
      /** User Account Id */
      user_account_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /** Access Token */
      access_token?: string | null;
      /** Secret */
      secret?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /** User Id */
      user_id?: string | null;
    };
    /** AdAccountRead */
    AdAccountRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** User Account Id */
      user_account_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** BillingRead */
    BillingRead: {
      /** Customer Id */
      customer_id?: string | null;
      /** Subscription Id */
      subscription_id?: string | null;
      /** Is Account Paid */
      is_account_paid: boolean;
      /** On Hold */
      on_hold: boolean;
      /** Trial Expiry */
      trial_expiry?: string | null;
    };
    /** BillingUpdate */
    BillingUpdate: {
      /** Customer Id */
      customer_id?: string | null;
      /** Subscription Id */
      subscription_id?: string | null;
      /** Is Account Paid */
      is_account_paid?: boolean | null;
      /** On Hold */
      on_hold?: boolean | null;
    };
    /** Body_upload_media_api_v1_media_upload_post */
    Body_upload_media_api_v1_media_upload_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** ConnectionResult */
    ConnectionResult: {
      /** Detail */
      detail: string;
      /**
       * Pages Connected
       * @default 0
       */
      pages_connected?: number;
    };
    /** FacebookConnectResponse */
    FacebookConnectResponse: {
      /** Authorize Url */
      authorize_url: string;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       */
      status?: string;
      /** Version */
      version: string;
    };
    /** LeadCreate */
    LeadCreate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /**
       * Is Phone Call Allowed
       * @default false
       */
      is_phone_call_allowed?: boolean;
      /**
       * Is Email Allowed
       * @default false
       */
      is_email_allowed?: boolean;
      /**
       * Is Text Allowed
       * @default false
       */
      is_text_allowed?: boolean;
      /**
       * Is Member
       * @default false
       */
      is_member?: boolean;
    };
    /** LeadRead */
    LeadRead: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /**
       * Is Phone Call Allowed
       * @default false
       */
      is_phone_call_allowed?: boolean;
      /**
       * Is Email Allowed
       * @default false
       */
      is_email_allowed?: boolean;
      /**
       * Is Text Allowed
       * @default false
       */
      is_text_allowed?: boolean;
      /**
       * Is Member
       * @default false
       */
      is_member?: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** LeadUpdate */
    LeadUpdate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /** Email */
      email?: string | null;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /** Is Phone Call Allowed */
      is_phone_call_allowed?: boolean | null;
      /** Is Email Allowed */
      is_email_allowed?: boolean | null;
      /** Is Text Allowed */
      is_text_allowed?: boolean | null;
      /** Is Member */
      is_member?: boolean | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MediaUploadResponse */
    MediaUploadResponse: {
      /** Url */
      url: string;
      /** Key */
      key: string;
    };
    /** MessageResponse */
    MessageResponse: {
      /** Detail */
      detail: string;
    };
    /** PlanRead */
    PlanRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name?: string | null;
      /** Type */
      type?: string | null;
      /** Price */
      price: string;
      /** Billing Period */
      billing_period?: string | null;
      /** Tax */
      tax: string;
      /** Total */
      total: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Account Name */
      account_name?: string | null;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /** ScheduledPostCreate */
    ScheduledPostCreate: {
      /**
       * Social Media Id
       * Format: uuid
       */
      social_media_id: string;
      /**
       * Platform
       * @default facebook
       */
      platform?: string;
      /** Message */
      message?: string | null;
      /** Link */
      link?: string | null;
      /** Image Url */
      image_url?: string | null;
      /**
       * Scheduled At
       * Format: date-time
       */
      scheduled_at: string;
    };
    /** ScheduledPostRead */
    ScheduledPostRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Social Media Id
       * Format: uuid
       */
      social_media_id: string;
      /** Platform */
      platform: string;
      /** Message */
      message?: string | null;
      /** Link */
      link?: string | null;
      /** Image Url */
      image_url?: string | null;
      /**
       * Scheduled At
       * Format: date-time
       */
      scheduled_at: string;
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /** Last Error */
      last_error?: string | null;
      /** External Post Id */
      external_post_id?: string | null;
    };
    /** SocialMediaCreate */
    SocialMediaCreate: {
      /** Page Id */
      page_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type: string;
      /** Access Token */
      access_token?: string | null;
      /** Secret */
      secret?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /** User Id */
      user_id?: string | null;
    };
    /** SocialMediaRead */
    SocialMediaRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Page Id */
      page_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** SubscriptionRequest */
    SubscriptionRequest: {
      /** Price Id */
      price_id: string;
    };
    /** SubscriptionResult */
    SubscriptionResult: {
      /** Subscription Id */
      subscription_id: string;
      /** Status */
      status: string;
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Email Confirmed */
      email_confirmed: boolean;
      /** Account Id */
      account_id?: string | null;
      /**
       * Roles
       * @default []
       */
      roles?: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Register */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Refresh */
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      cookie?: {
        refresh_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Email */
  verify_email_api_v1_auth_verify_email_get: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Forgot Password */
  forgot_password_api_v1_auth_forgot_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset Password */
  reset_password_api_v1_auth_reset_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Change Password */
  change_password_api_v1_auth_change_password_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Account */
  get_account_api_v1_account_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Account */
  update_account_api_v1_account_put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Plan */
  get_plan_api_v1_plans__name__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        name: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlanRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Leads */
  list_leads_api_v1_leads_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Lead */
  create_lead_api_v1_leads_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Search Leads */
  search_leads_api_v1_leads_search_get: {
    parameters: {
      query?: {
        name?: string | null;
        email?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Lead */
  get_lead_api_v1_leads__lead_id__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Lead */
  update_lead_api_v1_leads__lead_id__put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Lead */
  delete_lead_api_v1_leads__lead_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Tokens */
  list_tokens_api_v1_social_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Save Token */
  save_token_api_v1_social_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SocialMediaCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Token By Platform */
  get_token_by_platform_api_v1_social__platform__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        platform: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Token */
  delete_token_api_v1_social__token_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        token_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Ad Accounts */
  list_ad_accounts_api_v1_ad_accounts_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdAccountRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Save Ad Account */
  save_ad_account_api_v1_ad_accounts_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdAccountCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AdAccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Billing */
  get_billing_api_v1_billing_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BillingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Billing */
  update_billing_api_v1_billing_put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BillingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BillingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Facebook Connect */
  facebook_connect_api_v1_integrations_facebook_connect_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FacebookConnectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Facebook Callback */
  facebook_callback_api_v1_integrations_facebook_callback_get: {
    parameters: {
      query: {
        code: string;
        state: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConnectionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Subscription */
  create_subscription_api_v1_payments_create_subscription_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscriptionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SubscriptionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stripe Webhook */
  stripe_webhook_api_v1_payments_webhook_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Upload Media */
  upload_media_api_v1_media_upload_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_media_api_v1_media_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MediaUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Posts */
  list_posts_api_v1_scheduled_posts_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduledPostRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Post */
  create_post_api_v1_scheduled_posts_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduledPostCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScheduledPostRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Post */
  get_post_api_v1_scheduled_posts__post_id__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        post_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduledPostRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cancel Post */
  cancel_post_api_v1_scheduled_posts__post_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        post_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
