/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Health
     * @description Liveness — the process is up (no dependencies checked).
     */
    get: operations["health_health_get"];
  };
  "/readyz": {
    /**
     * Readyz
     * @description Readiness — verifies the database is reachable (for load balancers).
     */
    get: operations["readyz_readyz_get"];
  };
  "/api/v1/auth/register": {
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/refresh": {
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/verify-email": {
    /** Verify Email */
    get: operations["verify_email_api_v1_auth_verify_email_get"];
  };
  "/api/v1/auth/forgot-password": {
    /** Forgot Password */
    post: operations["forgot_password_api_v1_auth_forgot_password_post"];
  };
  "/api/v1/auth/reset-password": {
    /** Reset Password */
    post: operations["reset_password_api_v1_auth_reset_password_post"];
  };
  "/api/v1/auth/change-password": {
    /** Change Password */
    post: operations["change_password_api_v1_auth_change_password_post"];
  };
  "/api/v1/auth/change-email": {
    /** Change Email */
    post: operations["change_email_api_v1_auth_change_email_post"];
  };
  "/api/v1/auth/personal-data": {
    /**
     * Export Personal Data
     * @description GDPR data export — everything we hold about the user (excludes secrets).
     */
    get: operations["export_personal_data_api_v1_auth_personal_data_get"];
  };
  "/api/v1/auth/delete-account": {
    /**
     * Delete Account
     * @description GDPR delete — verify password, then soft-delete and scrub PII.
     */
    post: operations["delete_account_api_v1_auth_delete_account_post"];
  };
  "/api/v1/account": {
    /** Get Account */
    get: operations["get_account_api_v1_account_get"];
    /** Update Account */
    put: operations["update_account_api_v1_account_put"];
  };
  "/api/v1/account/usage": {
    /** Account Usage */
    get: operations["account_usage_api_v1_account_usage_get"];
  };
  "/api/v1/plans/{name}": {
    /** Get Plan */
    get: operations["get_plan_api_v1_plans__name__get"];
  };
  "/api/v1/leads": {
    /** List Leads */
    get: operations["list_leads_api_v1_leads_get"];
    /** Create Lead */
    post: operations["create_lead_api_v1_leads_post"];
  };
  "/api/v1/leads/search": {
    /** Search Leads */
    get: operations["search_leads_api_v1_leads_search_get"];
  };
  "/api/v1/leads/{lead_id}": {
    /** Get Lead */
    get: operations["get_lead_api_v1_leads__lead_id__get"];
    /** Update Lead */
    put: operations["update_lead_api_v1_leads__lead_id__put"];
    /** Delete Lead */
    delete: operations["delete_lead_api_v1_leads__lead_id__delete"];
  };
  "/api/v1/social": {
    /** List Tokens */
    get: operations["list_tokens_api_v1_social_get"];
    /** Save Token */
    post: operations["save_token_api_v1_social_post"];
  };
  "/api/v1/social/{platform}": {
    /** Get Token By Platform */
    get: operations["get_token_by_platform_api_v1_social__platform__get"];
  };
  "/api/v1/social/{token_id}": {
    /** Delete Token */
    delete: operations["delete_token_api_v1_social__token_id__delete"];
  };
  "/api/v1/social/{connection_id}/posts": {
    /** Page Posts */
    get: operations["page_posts_api_v1_social__connection_id__posts_get"];
    /** Create Page Post */
    post: operations["create_page_post_api_v1_social__connection_id__posts_post"];
  };
  "/api/v1/social/{connection_id}/insights": {
    /** Page Insights */
    get: operations["page_insights_api_v1_social__connection_id__insights_get"];
  };
  "/api/v1/social/{connection_id}/instagram-insights": {
    /** Instagram Insights */
    get: operations["instagram_insights_api_v1_social__connection_id__instagram_insights_get"];
  };
  "/api/v1/social/{connection_id}/sync-leads": {
    /**
     * Sync Lead Forms
     * @description Pull Facebook lead-gen form submissions into the Leads table (task 4.8).
     */
    post: operations["sync_lead_forms_api_v1_social__connection_id__sync_leads_post"];
  };
  "/api/v1/ad-accounts": {
    /** List Ad Accounts */
    get: operations["list_ad_accounts_api_v1_ad_accounts_get"];
    /** Save Ad Account */
    post: operations["save_ad_account_api_v1_ad_accounts_post"];
  };
  "/api/v1/ad-accounts/{conn_id}/campaigns": {
    /** List Campaigns */
    get: operations["list_campaigns_api_v1_ad_accounts__conn_id__campaigns_get"];
    /** Create Campaign */
    post: operations["create_campaign_api_v1_ad_accounts__conn_id__campaigns_post"];
  };
  "/api/v1/ad-accounts/{conn_id}/adsets": {
    /** List Adsets */
    get: operations["list_adsets_api_v1_ad_accounts__conn_id__adsets_get"];
    /** Create Adset */
    post: operations["create_adset_api_v1_ad_accounts__conn_id__adsets_post"];
  };
  "/api/v1/ad-accounts/{conn_id}/ads": {
    /** List Ads */
    get: operations["list_ads_api_v1_ad_accounts__conn_id__ads_get"];
    /** Create Ad */
    post: operations["create_ad_api_v1_ad_accounts__conn_id__ads_post"];
  };
  "/api/v1/ad-accounts/{conn_id}/targeting-search": {
    /** Targeting Search */
    get: operations["targeting_search_api_v1_ad_accounts__conn_id__targeting_search_get"];
  };
  "/api/v1/ad-accounts/{conn_id}/location-search": {
    /** Location Search */
    get: operations["location_search_api_v1_ad_accounts__conn_id__location_search_get"];
  };
  "/api/v1/billing": {
    /** Get Billing */
    get: operations["get_billing_api_v1_billing_get"];
    /** Update Billing */
    put: operations["update_billing_api_v1_billing_put"];
  };
  "/api/v1/integrations/facebook/connect": {
    /** Facebook Connect */
    get: operations["facebook_connect_api_v1_integrations_facebook_connect_get"];
  };
  "/api/v1/integrations/facebook/callback": {
    /** Facebook Callback */
    get: operations["facebook_callback_api_v1_integrations_facebook_callback_get"];
  };
  "/api/v1/payments/create-subscription": {
    /** Create Subscription */
    post: operations["create_subscription_api_v1_payments_create_subscription_post"];
  };
  "/api/v1/payments/portal": {
    /** Billing Portal */
    post: operations["billing_portal_api_v1_payments_portal_post"];
  };
  "/api/v1/payments/webhook": {
    /** Stripe Webhook */
    post: operations["stripe_webhook_api_v1_payments_webhook_post"];
  };
  "/api/v1/media": {
    /** List Media */
    get: operations["list_media_api_v1_media_get"];
  };
  "/api/v1/media/upload": {
    /** Upload Media */
    post: operations["upload_media_api_v1_media_upload_post"];
  };
  "/api/v1/media/file/{key}": {
    /**
     * Serve File
     * @description Serve a local-storage file (dev). Tenant-scoped by the key prefix.
     */
    get: operations["serve_file_api_v1_media_file__key__get"];
  };
  "/api/v1/scheduled-posts": {
    /** List Posts */
    get: operations["list_posts_api_v1_scheduled_posts_get"];
    /** Create Post */
    post: operations["create_post_api_v1_scheduled_posts_post"];
  };
  "/api/v1/scheduled-posts/{post_id}": {
    /** Get Post */
    get: operations["get_post_api_v1_scheduled_posts__post_id__get"];
    /** Cancel Post */
    delete: operations["cancel_post_api_v1_scheduled_posts__post_id__delete"];
  };
  "/api/v1/team": {
    /** List Team */
    get: operations["list_team_api_v1_team_get"];
    /** Invite Member */
    post: operations["invite_member_api_v1_team_post"];
  };
  "/api/v1/team/{user_id}": {
    /** Remove Member */
    delete: operations["remove_member_api_v1_team__user_id__delete"];
  };
  "/api/v1/roles": {
    /** List Roles */
    get: operations["list_roles_api_v1_roles_get"];
    /** Create Role */
    post: operations["create_role_api_v1_roles_post"];
  };
  "/api/v1/auth/2fa/setup": {
    /** Setup */
    post: operations["setup_api_v1_auth_2fa_setup_post"];
  };
  "/api/v1/auth/2fa/enable": {
    /** Enable */
    post: operations["enable_api_v1_auth_2fa_enable_post"];
  };
  "/api/v1/auth/2fa/disable": {
    /** Disable */
    post: operations["disable_api_v1_auth_2fa_disable_post"];
  };
  "/api/v1/auth/2fa/verify": {
    /**
     * Verify Login
     * @description Login step 2: validate the TOTP / recovery code against the challenge cookie.
     */
    post: operations["verify_login_api_v1_auth_2fa_verify_post"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccountRead */
    AccountRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Account Name */
      account_name?: string | null;
      /** Account Type */
      account_type?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Users Limit */
      users_limit?: string | null;
      /** Logo */
      logo?: string | null;
      /** Trial Expiry */
      trial_expiry?: string | null;
      /** Is Account Paid */
      is_account_paid: boolean;
      /** On Hold */
      on_hold: boolean;
    };
    /** AccountUpdate */
    AccountUpdate: {
      /** Account Name */
      account_name?: string | null;
      /** Account Type */
      account_type?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Logo */
      logo?: string | null;
    };
    /** AdAccountCreate */
    AdAccountCreate: {
      /** User Account Id */
      user_account_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /** Access Token */
      access_token?: string | null;
      /** Secret */
      secret?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /** User Id */
      user_id?: string | null;
    };
    /** AdAccountRead */
    AdAccountRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** User Account Id */
      user_account_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** AdCreateInput */
    AdCreateInput: {
      /** Name */
      name: string;
      /** Adset Id */
      adset_id: string;
      /** Page Id */
      page_id: string;
      /** Message */
      message: string;
      /** Link */
      link: string;
      /** Headline */
      headline?: string | null;
      /** Image Url */
      image_url?: string | null;
      /**
       * Status
       * @default PAUSED
       */
      status?: string;
    };
    /** AdsetCreateInput */
    AdsetCreateInput: {
      /** Name */
      name: string;
      /** Campaign Id */
      campaign_id: string;
      /**
       * Daily Budget
       * @description minor currency units (e.g. cents)
       */
      daily_budget: number;
      /**
       * Optimization Goal
       * @default LINK_CLICKS
       */
      optimization_goal?: string;
      /**
       * Billing Event
       * @default IMPRESSIONS
       */
      billing_event?: string;
      /**
       * Age Min
       * @default 18
       */
      age_min?: number;
      /**
       * Age Max
       * @default 65
       */
      age_max?: number;
      /**
       * Country Codes
       * @default [
       *   "US"
       * ]
       */
      country_codes?: string[];
      /**
       * Interest Ids
       * @default []
       */
      interest_ids?: string[];
      /**
       * Status
       * @default PAUSED
       */
      status?: string;
    };
    /** BillingRead */
    BillingRead: {
      /** Customer Id */
      customer_id?: string | null;
      /** Subscription Id */
      subscription_id?: string | null;
      /** Is Account Paid */
      is_account_paid: boolean;
      /** On Hold */
      on_hold: boolean;
      /** Trial Expiry */
      trial_expiry?: string | null;
    };
    /** BillingUpdate */
    BillingUpdate: {
      /** Customer Id */
      customer_id?: string | null;
      /** Subscription Id */
      subscription_id?: string | null;
      /** Is Account Paid */
      is_account_paid?: boolean | null;
      /** On Hold */
      on_hold?: boolean | null;
    };
    /** Body_upload_media_api_v1_media_upload_post */
    Body_upload_media_api_v1_media_upload_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** CampaignCreateInput */
    CampaignCreateInput: {
      /** Name */
      name: string;
      /**
       * Objective
       * @default LINK_CLICKS
       */
      objective?: string;
      /**
       * Status
       * @default PAUSED
       */
      status?: string;
    };
    /** ChangeEmailRequest */
    ChangeEmailRequest: {
      /**
       * New Email
       * Format: email
       */
      new_email: string;
      /** Password */
      password: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** CodeRequest */
    CodeRequest: {
      /** Code */
      code: string;
    };
    /** ConnectionResult */
    ConnectionResult: {
      /** Detail */
      detail: string;
      /**
       * Pages Connected
       * @default 0
       */
      pages_connected?: number;
    };
    /** DeleteAccountRequest */
    DeleteAccountRequest: {
      /** Password */
      password: string;
    };
    /** FacebookConnectResponse */
    FacebookConnectResponse: {
      /** Authorize Url */
      authorize_url: string;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       */
      status?: string;
      /** Version */
      version: string;
    };
    /** LeadCreate */
    LeadCreate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /**
       * Is Phone Call Allowed
       * @default false
       */
      is_phone_call_allowed?: boolean;
      /**
       * Is Email Allowed
       * @default false
       */
      is_email_allowed?: boolean;
      /**
       * Is Text Allowed
       * @default false
       */
      is_text_allowed?: boolean;
      /**
       * Is Member
       * @default false
       */
      is_member?: boolean;
    };
    /** LeadRead */
    LeadRead: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /**
       * Is Phone Call Allowed
       * @default false
       */
      is_phone_call_allowed?: boolean;
      /**
       * Is Email Allowed
       * @default false
       */
      is_email_allowed?: boolean;
      /**
       * Is Text Allowed
       * @default false
       */
      is_text_allowed?: boolean;
      /**
       * Is Member
       * @default false
       */
      is_member?: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** LeadUpdate */
    LeadUpdate: {
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /** Email */
      email?: string | null;
      /** Primary Phone */
      primary_phone?: string | null;
      /** Secondary Phone */
      secondary_phone?: string | null;
      /** Date Of Birth */
      date_of_birth?: string | null;
      /** Gender */
      gender?: string | null;
      /** Address */
      address?: string | null;
      /** City */
      city?: string | null;
      /** Province */
      province?: string | null;
      /** Country */
      country?: string | null;
      /** Postal Code */
      postal_code?: string | null;
      /** Lead Source */
      lead_source?: string | null;
      /** Is Phone Call Allowed */
      is_phone_call_allowed?: boolean | null;
      /** Is Email Allowed */
      is_email_allowed?: boolean | null;
      /** Is Text Allowed */
      is_text_allowed?: boolean | null;
      /** Is Member */
      is_member?: boolean | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /**
       * Two Factor Required
       * @default false
       */
      two_factor_required?: boolean;
      user?: components["schemas"]["UserRead"] | null;
    };
    /** MediaAssetRead */
    MediaAssetRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Url */
      url: string;
      /** Kind */
      kind: string;
      /** Content Type */
      content_type?: string | null;
    };
    /** MediaUploadResponse */
    MediaUploadResponse: {
      /** Url */
      url: string;
      /** Key */
      key: string;
    };
    /** MessageResponse */
    MessageResponse: {
      /** Detail */
      detail: string;
    };
    /** PagePostInput */
    PagePostInput: {
      /**
       * Message
       * @default
       */
      message?: string;
      /** Link */
      link?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Video Url */
      video_url?: string | null;
    };
    /** Page[LeadRead] */
    Page_LeadRead_: {
      /** Items */
      items: components["schemas"]["LeadRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[MediaAssetRead] */
    Page_MediaAssetRead_: {
      /** Items */
      items: components["schemas"]["MediaAssetRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[ScheduledPostRead] */
    Page_ScheduledPostRead_: {
      /** Items */
      items: components["schemas"]["ScheduledPostRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** PlanRead */
    PlanRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name?: string | null;
      /** Type */
      type?: string | null;
      /** Price */
      price: string;
      /** Billing Period */
      billing_period?: string | null;
      /** Tax */
      tax: string;
      /** Total */
      total: string;
    };
    /** PortalSession */
    PortalSession: {
      /** Url */
      url: string;
    };
    /** RecoveryCodesResponse */
    RecoveryCodesResponse: {
      /** Recovery Codes */
      recovery_codes: string[];
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Account Name */
      account_name?: string | null;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /** RoleCreate */
    RoleCreate: {
      /** Name */
      name: string;
    };
    /** RoleRead */
    RoleRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** ScheduledPostCreate */
    ScheduledPostCreate: {
      /**
       * Social Media Id
       * Format: uuid
       */
      social_media_id: string;
      /**
       * Platform
       * @default facebook
       */
      platform?: string;
      /** Message */
      message?: string | null;
      /** Link */
      link?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Video Url */
      video_url?: string | null;
      /**
       * Scheduled At
       * Format: date-time
       */
      scheduled_at: string;
    };
    /** ScheduledPostRead */
    ScheduledPostRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
      /**
       * Social Media Id
       * Format: uuid
       */
      social_media_id: string;
      /** Platform */
      platform: string;
      /** Message */
      message?: string | null;
      /** Link */
      link?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Video Url */
      video_url?: string | null;
      /**
       * Scheduled At
       * Format: date-time
       */
      scheduled_at: string;
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /** Last Error */
      last_error?: string | null;
      /** External Post Id */
      external_post_id?: string | null;
    };
    /** SocialMediaCreate */
    SocialMediaCreate: {
      /** Page Id */
      page_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type: string;
      /** Access Token */
      access_token?: string | null;
      /** Secret */
      secret?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /** User Id */
      user_id?: string | null;
    };
    /** SocialMediaRead */
    SocialMediaRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Page Id */
      page_id?: string | null;
      /** Name */
      name?: string | null;
      /** Image */
      image?: string | null;
      /** Type */
      type?: string | null;
      /** Token Expiry Date */
      token_expiry_date?: string | null;
      /** Email */
      email?: string | null;
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string;
    };
    /** SubscriptionRequest */
    SubscriptionRequest: {
      /** Price Id */
      price_id: string;
      /**
       * Plan
       * @default premium
       */
      plan?: string;
    };
    /** SubscriptionResult */
    SubscriptionResult: {
      /** Subscription Id */
      subscription_id: string;
      /** Status */
      status: string;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** TeamInvite */
    TeamInvite: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string | null;
      /**
       * Role
       * @default User
       */
      role?: string;
    };
    /** TeamMemberRead */
    TeamMemberRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Email Confirmed */
      email_confirmed: boolean;
      /** Is Deleted */
      is_deleted: boolean;
      /**
       * Roles
       * @default []
       */
      roles?: string[];
    };
    /** TwoFASetupResponse */
    TwoFASetupResponse: {
      /** Secret */
      secret: string;
      /** Otpauth Uri */
      otpauth_uri: string;
    };
    /** UsageItem */
    UsageItem: {
      /** Used */
      used: number;
      /** Limit */
      limit?: number | null;
    };
    /** UsageResponse */
    UsageResponse: {
      /** Plan */
      plan: string;
      seats: components["schemas"]["UsageItem"];
      social_sets: components["schemas"]["UsageItem"];
      scheduled_posts: components["schemas"]["UsageItem"];
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Email Confirmed */
      email_confirmed: boolean;
      /**
       * Two Factor Enabled
       * @default false
       */
      two_factor_enabled?: boolean;
      /** Account Id */
      account_id?: string | null;
      /**
       * Roles
       * @default []
       */
      roles?: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health
   * @description Liveness — the process is up (no dependencies checked).
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /**
   * Readyz
   * @description Readiness — verifies the database is reachable (for load balancers).
   */
  readyz_readyz_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** Register */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Refresh */
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      cookie?: {
        refresh_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Email */
  verify_email_api_v1_auth_verify_email_get: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Forgot Password */
  forgot_password_api_v1_auth_forgot_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset Password */
  reset_password_api_v1_auth_reset_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Change Password */
  change_password_api_v1_auth_change_password_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Change Email */
  change_email_api_v1_auth_change_email_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Personal Data
   * @description GDPR data export — everything we hold about the user (excludes secrets).
   */
  export_personal_data_api_v1_auth_personal_data_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Account
   * @description GDPR delete — verify password, then soft-delete and scrub PII.
   */
  delete_account_api_v1_auth_delete_account_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteAccountRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Account */
  get_account_api_v1_account_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Account */
  update_account_api_v1_account_put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Account Usage */
  account_usage_api_v1_account_usage_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UsageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Plan */
  get_plan_api_v1_plans__name__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        name: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlanRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Leads */
  list_leads_api_v1_leads_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        source?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_LeadRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Lead */
  create_lead_api_v1_leads_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Search Leads */
  search_leads_api_v1_leads_search_get: {
    parameters: {
      query?: {
        name?: string | null;
        email?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Lead */
  get_lead_api_v1_leads__lead_id__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Lead */
  update_lead_api_v1_leads__lead_id__put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Lead */
  delete_lead_api_v1_leads__lead_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        lead_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Tokens */
  list_tokens_api_v1_social_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Save Token */
  save_token_api_v1_social_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SocialMediaCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Token By Platform */
  get_token_by_platform_api_v1_social__platform__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        platform: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SocialMediaRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Token */
  delete_token_api_v1_social__token_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        token_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Page Posts */
  page_posts_api_v1_social__connection_id__posts_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Page Post */
  create_page_post_api_v1_social__connection_id__posts_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PagePostInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Page Insights */
  page_insights_api_v1_social__connection_id__insights_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Instagram Insights */
  instagram_insights_api_v1_social__connection_id__instagram_insights_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Sync Lead Forms
   * @description Pull Facebook lead-gen form submissions into the Leads table (task 4.8).
   */
  sync_lead_forms_api_v1_social__connection_id__sync_leads_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        connection_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Ad Accounts */
  list_ad_accounts_api_v1_ad_accounts_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdAccountRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Save Ad Account */
  save_ad_account_api_v1_ad_accounts_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdAccountCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AdAccountRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Campaigns */
  list_campaigns_api_v1_ad_accounts__conn_id__campaigns_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Campaign */
  create_campaign_api_v1_ad_accounts__conn_id__campaigns_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CampaignCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Adsets */
  list_adsets_api_v1_ad_accounts__conn_id__adsets_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Adset */
  create_adset_api_v1_ad_accounts__conn_id__adsets_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdsetCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Ads */
  list_ads_api_v1_ad_accounts__conn_id__ads_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Ad */
  create_ad_api_v1_ad_accounts__conn_id__ads_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdCreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Targeting Search */
  targeting_search_api_v1_ad_accounts__conn_id__targeting_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Location Search */
  location_search_api_v1_ad_accounts__conn_id__location_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        conn_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Billing */
  get_billing_api_v1_billing_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BillingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Billing */
  update_billing_api_v1_billing_put: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BillingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BillingRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Facebook Connect */
  facebook_connect_api_v1_integrations_facebook_connect_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FacebookConnectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Facebook Callback */
  facebook_callback_api_v1_integrations_facebook_callback_get: {
    parameters: {
      query: {
        code: string;
        state: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConnectionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Subscription */
  create_subscription_api_v1_payments_create_subscription_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscriptionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SubscriptionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Billing Portal */
  billing_portal_api_v1_payments_portal_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PortalSession"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stripe Webhook */
  stripe_webhook_api_v1_payments_webhook_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** List Media */
  list_media_api_v1_media_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_MediaAssetRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload Media */
  upload_media_api_v1_media_upload_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_media_api_v1_media_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MediaUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Serve File
   * @description Serve a local-storage file (dev). Tenant-scoped by the key prefix.
   */
  serve_file_api_v1_media_file__key__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        key: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Posts */
  list_posts_api_v1_scheduled_posts_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ScheduledPostRead_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Post */
  create_post_api_v1_scheduled_posts_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduledPostCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScheduledPostRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Post */
  get_post_api_v1_scheduled_posts__post_id__get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        post_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduledPostRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cancel Post */
  cancel_post_api_v1_scheduled_posts__post_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        post_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Team */
  list_team_api_v1_team_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TeamMemberRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Invite Member */
  invite_member_api_v1_team_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamInvite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TeamMemberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Member */
  remove_member_api_v1_team__user_id__delete: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Roles */
  list_roles_api_v1_roles_get: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RoleRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Role */
  create_role_api_v1_roles_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["RoleRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Setup */
  setup_api_v1_auth_2fa_setup_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TwoFASetupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Enable */
  enable_api_v1_auth_2fa_enable_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecoveryCodesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Disable */
  disable_api_v1_auth_2fa_disable_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Verify Login
   * @description Login step 2: validate the TOTP / recovery code against the challenge cookie.
   */
  verify_login_api_v1_auth_2fa_verify_post: {
    parameters: {
      cookie?: {
        twofa_token?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
